# Generated by Django 2.1.1 on 2018-09-27 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingress', '0002_auto_20180915_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingress',
            options={'ordering': ['-id'], 'verbose_name': 'Despacho', 'verbose_name_plural': 'Despachos'},
        ),
        migrations.AddField(
            model_name='ingress',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
