# Generated by Django 2.1.1 on 2018-10-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0002_ingress_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
