# Generated by Django 2.1.1 on 2018-09-28 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0003_auto_20180927_0122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-name'], 'verbose_name': 'Tipo', 'verbose_name_plural': 'Tipos'},
        ),
    ]
