# Generated by Django 2.1.1 on 2018-10-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0003_inventory_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
