# Generated by Django 2.1.1 on 2018-10-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0005_auto_20181002_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='cant',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
