# Generated by Django 2.1.1 on 2018-10-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0005_auto_20181003_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='diferencia',
            field=models.IntegerField(default=0),
        ),
    ]
