# Generated by Django 2.1.1 on 2018-10-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0006_inventory_diferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingress',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
