# Generated by Django 2.1.1 on 2018-10-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0007_ingress_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=9, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=9, verbose_name='Precio'),
        ),
    ]
