# Generated by Django 2.1.1 on 2018-10-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0008_auto_20181005_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=9),
        ),
    ]
