# Generated by Django 2.1.1 on 2018-10-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0011_auto_20181010_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='ruc',
            field=models.CharField(max_length=13, verbose_name='Ruc'),
        ),
    ]
