# Generated by Django 2.1.1 on 2018-10-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0012_auto_20181010_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='ruc',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Ruc'),
        ),
    ]
