# Generated by Django 2.1.1 on 2018-10-22 03:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_bodega'),
        ('ingress', '0013_auto_20181010_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='document/%Y/%m/%d', verbose_name='Imagen')),
                ('bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.Bodega', verbose_name='Bodega')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date_joined'],
            },
        ),
    ]
