# Generated by Django 2.1.1 on 2018-10-22 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0014_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha'),
        ),
    ]
