# Generated by Django 2.1.1 on 2018-10-22 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0015_auto_20181021_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fechax'),
        ),
    ]
