# Generated by Django 2.1.1 on 2018-10-31 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0016_auto_20181022_0815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingress',
            options={'ordering': ['-id'], 'verbose_name': 'Ingreso', 'verbose_name_plural': 'Ingresos'},
        ),
    ]
