# Generated by Django 2.1.1 on 2018-09-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessusers',
            name='hostname',
            field=models.TextField(default='inplanettics002-web'),
        ),
        migrations.AlterField(
            model_name='database',
            name='hostname',
            field=models.TextField(blank=True, default='inplanettics002-web', null=True),
        ),
    ]
