# Generated by Django 2.1.1 on 2018-09-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_auto_20180911_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessusers',
            name='hostname',
            field=models.TextField(default='DESKTOP-8I2OMDM'),
        ),
        migrations.AlterField(
            model_name='database',
            name='hostname',
            field=models.TextField(blank=True, default='DESKTOP-8I2OMDM', null=True),
        ),
    ]
