# Generated by Django 2.1.1 on 2018-09-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_auto_20180911_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessusers',
            name='hostname',
            field=models.TextField(default='ProBook-4440s'),
        ),
        migrations.AlterField(
            model_name='database',
            name='hostname',
            field=models.TextField(blank=True, default='ProBook-4440s', null=True),
        ),
    ]
