# Generated by Django 2.1.1 on 2018-10-03 09:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('proprietor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Propietario')),
                ('ruc', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Ruc')),
                ('phone', models.CharField(blank=True, max_length=7, null=True, unique=True, verbose_name='Teléfono Convencional')),
                ('mobile', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Teléfono Celular')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True, verbose_name='Correo Electrónico')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='library/%Y/%m/%d', verbose_name='Logo')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('mission', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Misión')),
                ('vision', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Visión')),
                ('about_us', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Quienes Somos')),
                ('schedule', models.CharField(max_length=255, verbose_name='Horario')),
            ],
            options={
                'verbose_name': 'Compañia',
                'verbose_name_plural': 'Compañias',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, default='Sin detalles', max_length=500, null=True, verbose_name='Detalles')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Valor')),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.Company')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Serie')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Valor')),
                ('guarantee', models.IntegerField(default=0, verbose_name='Garantía (Años)')),
                ('dep', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.Company')),
            ],
            options={
                'verbose_name': 'Herramienta',
                'verbose_name_plural': 'Herramientas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TypeExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de Gasto',
                'verbose_name_plural': 'Tipos de Gastos',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='expenses',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.TypeExpense', verbose_name='Tipo de Gasto'),
        ),
    ]
