# Generated by Django 2.1.1 on 2018-09-11 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='description',
            new_name='proprietor',
        ),
    ]
