# Generated by Django 2.1.1 on 2018-09-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180910_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Teléfono Celular'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True, verbose_name='Teléfono Convencional'),
        ),
    ]
