# Generated by Django 2.1.1 on 2018-09-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20180910_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='proprietor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Propietario'),
        ),
    ]
