# Generated by Django 2.1.1 on 2018-09-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20180910_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='dep',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='tools',
            name='guarantee',
            field=models.IntegerField(default=0, verbose_name='Garantía (Años)'),
        ),
    ]
