# Generated by Django 2.1.1 on 2018-09-11 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='phone',
            new_name='mobile',
        ),
    ]
