# Generated by Django 2.1.1 on 2018-10-06 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20181003_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesservices',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Sales'),
        ),
        migrations.AlterField(
            model_name='salesservices',
            name='serv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Services'),
        ),
    ]
