# Generated by Django 2.1.1 on 2018-10-08 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20181005_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesMedidores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeracion', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='numeracion')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Sales')),
            ],
        ),
        migrations.CreateModel(
            name='SalesSellos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeracion', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='numeracion')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Sales')),
            ],
        ),
    ]
