# Generated by Django 2.1.1 on 2018-10-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesmedidores_salessellos'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmedidores',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salessellos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
