# Generated by Django 2.1.1 on 2018-09-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sales_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['-id'], 'verbose_name': 'Despacho', 'verbose_name_plural': 'Despachos'},
        ),
        migrations.AlterModelOptions(
            name='salesservices',
            options={'ordering': ['-id'], 'verbose_name': 'Detalle de la Despacho', 'verbose_name_plural': 'Detalle de las Despachos'},
        ),
        migrations.AlterField(
            model_name='sales',
            name='type',
            field=models.IntegerField(choices=[(1, 'Despacho'), (2, 'Pedido')], default=1),
        ),
    ]
