# Generated by Django 2.1.1 on 2018-10-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20180929_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='type',
            field=models.IntegerField(choices=[(1, 'Despacho')], default=1),
        ),
    ]
