# Generated by Django 2.1.1 on 2018-10-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20181002_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesproducts',
            name='cant',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesproducts',
            name='cant_ent',
            field=models.IntegerField(default=0),
        ),
    ]
