# Generated by Django 2.1.1 on 2018-10-09 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20181008_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidoresDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeracion', models.PositiveIntegerField(default=0, verbose_name='numeracion')),
                ('salesmedidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.SalesMedidores')),
            ],
        ),
        migrations.CreateModel(
            name='SellosDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeracion', models.PositiveIntegerField(default=0, verbose_name='numeracion')),
                ('salessellos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.SalesSellos')),
            ],
        ),
    ]
