# Generated by Django 2.1.1 on 2018-10-11 20:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0013_auto_20181010_1136'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0010_client_bodega'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionMedidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantmed', models.IntegerField(default=0)),
                ('cantmsell', models.IntegerField(default=0)),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMedidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_delivery', models.DateField(default=datetime.datetime.now)),
                ('numeracion', models.PositiveIntegerField(default=0)),
                ('diferencia', models.IntegerField(default=0)),
                ('estado', models.BooleanField(default=False)),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.Client')),
                ('ing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.GestionMedidor')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingress.Product')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='medidoresdetalle',
            name='salesmedidor',
        ),
        migrations.RemoveField(
            model_name='salesmedidores',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='salessellos',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='sellosdetalle',
            name='salessellos',
        ),
        migrations.DeleteModel(
            name='MedidoresDetalle',
        ),
        migrations.DeleteModel(
            name='SalesMedidores',
        ),
        migrations.DeleteModel(
            name='SalesSellos',
        ),
        migrations.DeleteModel(
            name='SellosDetalle',
        ),
    ]
