# Generated by Django 2.1.1 on 2018-10-11 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_auto_20181011_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorymedidor',
            old_name='ing',
            new_name='gestion',
        ),
        migrations.RemoveField(
            model_name='inventorymedidor',
            name='diferencia',
        ),
        migrations.AddField(
            model_name='inventorymedidor',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='inventorymedidor',
            name='distribuido',
            field=models.BooleanField(default=False),
        ),
    ]
