# Generated by Django 2.1.1 on 2018-10-15 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20181011_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='inventorymedidor',
            name='medtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sales.MedidorType'),
            preserve_default=False,
        ),
    ]
