# Generated by Django 2.1.1 on 2018-10-15 22:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0016_auto_20181015_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('date_delivery', models.DateField(default=datetime.datetime.now)),
                ('numeracion', models.PositiveIntegerField(default=0)),
                ('distribuido', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=False)),
                ('cli', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.Client')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.GestionMedidor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
