# Generated by Django 2.1.1 on 2018-10-16 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_inventorysello'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymedidor',
            name='gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.GestionMedidor'),
        ),
        migrations.AlterField(
            model_name='inventorysello',
            name='gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.GestionMedidor'),
        ),
    ]
