# Generated by Django 2.1.1 on 2018-10-19 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_auto_20181016_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymedidor',
            name='gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.GestionMedidor'),
        ),
        migrations.AlterField(
            model_name='inventorysello',
            name='gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.GestionMedidor'),
        ),
    ]
