# Generated by Django 2.1.1 on 2018-10-19 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_auto_20181019_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymedidor',
            name='gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.GestionMedidor'),
        ),
        migrations.AlterField(
            model_name='inventorysello',
            name='gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.GestionMedidor'),
        ),
    ]
