# Generated by Django 2.1.1 on 2018-10-19 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_auto_20181019_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymedidor',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.Sales'),
        ),
        migrations.AddField(
            model_name='inventorysello',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.Sales'),
        ),
    ]
