# Generated by Django 2.1.1 on 2018-10-31 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_auto_20181021_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymedidor',
            name='gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.GestionMedidor'),
        ),
        migrations.AlterField(
            model_name='inventorymedidor',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.Sales'),
        ),
        migrations.AlterField(
            model_name='inventorysello',
            name='gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.GestionMedidor'),
        ),
        migrations.AlterField(
            model_name='inventorysello',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.Sales'),
        ),
    ]
