# Generated by Django 2.1.1 on 2018-09-11 03:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=10, unique=True, verbose_name='Nombres')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('mobile', models.CharField(max_length=10, unique=True, verbose_name='Teléfono Celular')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('start_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de finalización')),
                ('rmu', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Valor')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Es activo?')),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.Company')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Faults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('details', models.CharField(blank=True, default='Sin detalles', max_length=1000, null=True, verbose_name='Detalles')),
                ('cont', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.Contracts', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Falta',
                'verbose_name_plural': 'Faltas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(choices=[('', '-----------'), (1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('dscto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cont', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.Contracts')),
            ],
            options={
                'verbose_name': 'Salario',
                'verbose_name_plural': 'Salarios',
                'ordering': ['id'],
            },
        ),
    ]
