# Generated by Django 2.1.1 on 2018-09-11 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20180910_2340'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=10, unique=True, verbose_name='Nombres')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('mobile', models.CharField(max_length=10, unique=True, verbose_name='Teléfono Celular')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='personal/%Y/%m/%d', verbose_name='Avatar')),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.Company')),
            ],
            options={
                'verbose_name_plural': 'Empleados',
                'verbose_name': 'Empleado',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='comp',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='names',
        ),
        migrations.AddField(
            model_name='contracts',
            name='pers',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='employees.Personal', verbose_name='Personal'),
            preserve_default=False,
        ),
    ]
