# Generated by Django 2.1.1 on 2018-09-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_personal_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='names',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombres'),
        ),
    ]
