# Generated by Django 2.1.1 on 2018-09-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20180911_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='falts',
            field=models.IntegerField(default=0),
        ),
    ]
